FROM frolvlad/alpine-oraclejdk8:slim
#FROM openjdk:8
VOLUME /tmp
COPY target/SpringBootElasticSearchDocker-0.0.1.jar SpringBootElasticSearchDocker.jar
ENTRYPOINT ["java","-jar","/SpringBootElasticSearchDocker.jar"]
