version: '2'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
      container_name: elasticsearch
      ports:
        - "9200:9200"
        
    spring-app:
        build:
          context: .
          dockerfile: dockerfile.spring
        ports:
          - "8080:8080"
        volumes:
          - .:/vol/development
        depends_on:
          - elasticsearch
         
